stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/wine-quality.csv
    outs:
    - data/raw/wine-quality.csv
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/wine-quality.csv
    outs:
    - data/processed/train_wine.csv
    - data/processed/test_wine.csv