stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/wine-quality.csv
    outs:
    - data/raw/wine-quality.csv