base:
  project: WineQuality-Project
  random_state: 42
  target_col: quality

data_source:
  s3_source: data_given/wine-quality.csv

load_data:
  raw_dataset: data/raw/wine-quality.csv

split_data:
  train_dataset: data/processed/train_wine.csv
  test_dataset: data/processed/test_wine.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.8
      l1_ratio: 0.8
      # alpha: 0.9
      # l1_ratio: 0.45
model_dir: saved_models

reports:
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet Regression
  run_name: mlops
  registered_model_name: ElasticNet
  remote_server_uri: http://127.0.0.1:5000