base:
  project: WineQuality-Project
  random_state: 42
  target_col: quality

data_source:
  s3_source: data_given/wine-quality.csv

load_data:
  raw_dataset: data/raw/wine-quality.csv

split_data:
  train_dataset: data/processed/train_wine.csv
  test_dataset: data/processed/test_wine.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.45
model_dir: saved_models

reports:
  params: reports/params.json
  scores: reports/scores.json